[0m12:19:50.190944 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107dee7e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e9af00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e9ac90>]}


============================== 12:19:50.194766 | 00efa6ad-482e-486f-9d85-85ce8794e9bb ==============================
[0m12:19:50.194766 [info ] [MainThread]: Running with dbt=1.10.0-b1
[0m12:19:50.195250 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/dharmatejasamudrala/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init reddit_dbt', 'send_anonymous_usage_stats': 'True'}
[0m12:19:50.207328 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/dharmatejasamudrala/.dbt')}
[0m12:19:50.207851 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:19:50.209655 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/include/starter_project
[0m12:19:50.215932 [info ] [MainThread]: 
Your new dbt project "reddit_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:19:50.216233 [info ] [MainThread]: Setting up your profile.
[0m12:20:28.497541 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m12:20:28.498556 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m12:21:59.717162 [info ] [MainThread]: Profile reddit_dbt written to /Users/dharmatejasamudrala/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:21:59.787296 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 129.65874, "process_in_blocks": "0", "process_kernel_time": 0.353683, "process_mem_max_rss": "109576192", "process_out_blocks": "0", "process_user_time": 1.350333}
[0m12:21:59.789872 [debug] [MainThread]: Command `dbt init` succeeded at 12:21:59.789000 after 129.66 seconds
[0m12:21:59.793041 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1010703e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107dee7e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f9b6b0>]}
[0m12:21:59.794556 [debug] [MainThread]: Flushing usage events
[0m12:22:00.389606 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:15:16.588901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107575880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ca32c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ca2ed0>]}


============================== 14:15:16.592673 | 6c124260-9556-4cd0-b8bc-dc8af618982e ==============================
[0m14:15:16.592673 [info ] [MainThread]: Running with dbt=1.10.0-b1
[0m14:15:16.593269 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/dharmatejasamudrala/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m14:15:16.593736 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/dharmatejasamudrala/reddit-etl/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:15:16.595116 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.06944325, "process_in_blocks": "0", "process_kernel_time": 0.190856, "process_mem_max_rss": "108134400", "process_out_blocks": "0", "process_user_time": 1.188709}
[0m14:15:16.595553 [debug] [MainThread]: Command `dbt run` failed at 14:15:16.595473 after 0.07 seconds
[0m14:15:16.595877 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105266f90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ca3050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ca31d0>]}
[0m14:15:16.596158 [debug] [MainThread]: Flushing usage events
[0m14:15:16.995403 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:15:36.035296 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107b604a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a97350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a96f90>]}


============================== 14:15:36.041201 | c3a97e05-b3c5-4edb-bbeb-350b13656d85 ==============================
[0m14:15:36.041201 [info ] [MainThread]: Running with dbt=1.10.0-b1
[0m14:15:36.041910 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/dharmatejasamudrala/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m14:15:36.042448 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/dharmatejasamudrala/reddit-etl/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:15:36.043750 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07436821, "process_in_blocks": "0", "process_kernel_time": 0.171418, "process_mem_max_rss": "105005056", "process_out_blocks": "0", "process_user_time": 1.18408}
[0m14:15:36.044456 [debug] [MainThread]: Command `dbt run` failed at 14:15:36.044359 after 0.08 seconds
[0m14:15:36.044952 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105a60290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110043e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a970b0>]}
[0m14:15:36.045347 [debug] [MainThread]: Flushing usage events
[0m14:15:36.162227 [debug] [MainThread]: An error was encountered while trying to flush usage events
